kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- pingfederate.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingfederate-engine-environment-variables
  envs:
    - env_vars.pingfederate-engine

secretGenerator:
- files:
  - pingfederate.lic
  name: pingfederate-license
  type: Opaque